#!/bin/bash
set -e

echo "=== QuEnAIS Installation ==="

# ── Check system requirements ─────────────────────────────────────────────────
echo "[0/6] Checking system requirements..."

command -v python || { echo "ERROR: python not found"; exit 1; }
command -v pip    || { echo "ERROR: pip not found"; exit 1; }
command -v git    || { echo "ERROR: git not found"; exit 1; }
command -v cargo  || { echo "ERROR: cargo not found. Install Rust: https://rustup.rs"; exit 1; }
command -v clang  || { echo "ERROR: clang not found. apt install clang  OR  module load clang"; exit 1; }

PYTHON_VERSION=$(python -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
echo "  Python $PYTHON_VERSION"

# ── Step 1: Base dependencies ─────────────────────────────────────────────────
# numpy/scipy MUST be installed before pyscf compiles
echo "[1/6] Installing base dependencies..."
pip install -r requirements-base.txt
echo "  ✓ base done"

# ── Step 2: Quantum dependencies ──────────────────────────────────────────────
# pyscf, qiskit, ffsim etc.
echo "[2/6] Installing quantum dependencies..."
pip install -r requirements-quantum.txt
echo "  ✓ quantum done"

# ── Step 3: Generate block2 wrapper ──────────────────────────────────────────
echo "[3/6] Generating block2 wrapper..."

BLOCK2_DIR=$(python -c "import block2, os; print(os.path.dirname(block2.__file__))")
BLOCK2_LIBS="${BLOCK2_DIR}.libs"
BLOCK2MAIN=$(python -c "import sys, os; print(os.path.join(os.path.dirname(sys.executable), 'block2main'))")
WRAPPER_PATH="$HOME/block2main_wrapper.sh"

CPU_VENDOR=$(grep -m1 'vendor_id' /proc/cpuinfo 2>/dev/null | awk '{print $3}')
echo "  CPU vendor: ${CPU_VENDOR:-unknown}"

if [ "$CPU_VENDOR" = "AuthenticAMD" ]; then
    echo "  AMD CPU detected — applying MKL workaround"
    cat > "$WRAPPER_PATH" << WRAPPER
#!/bin/bash
# Auto-generated by QuEnAIS install.sh — AMD MKL workaround
BLOCK2_LIBS=${BLOCK2_LIBS}

export LD_PRELOAD="\
\$BLOCK2_LIBS/libgomp-a34b3233.so.1.0.0:\
\$BLOCK2_LIBS/libmkl_avx2.so.1:\
\$BLOCK2_LIBS/libmkl_avx512.so.1:\
\$BLOCK2_LIBS/libmkl_core-a1f8e95a.so.1:\
\$BLOCK2_LIBS/libmkl_gnu_thread-76126a9d.so.1:\
\$BLOCK2_LIBS/libmkl_intel_lp64-eeafede9.so.1"

export MKL_THREADING_LAYER=GNU
export MKL_DEBUG_CPU_TYPE=5
export LD_LIBRARY_PATH=\$BLOCK2_LIBS:\$LD_LIBRARY_PATH

exec ${BLOCK2MAIN} "\$@"
WRAPPER
else
    echo "  Intel/other CPU — simple wrapper"
    cat > "$WRAPPER_PATH" << WRAPPER
#!/bin/bash
# Auto-generated by QuEnAIS install.sh
exec ${BLOCK2MAIN} "\$@"
WRAPPER
fi

chmod +x "$WRAPPER_PATH"
echo "  ✓ block2 wrapper → $WRAPPER_PATH"

# ── Step 4: Install ASF ───────────────────────────────────────────────────────
echo "[4/6] Installing ASF (Active Space Finder)..."
ASF_TMP=$(mktemp -d)
git clone https://github.com/HQSquantumsimulations/ActiveSpaceFinder.git "$ASF_TMP"
pip install "$ASF_TMP"
"$ASF_TMP/init_dmrgscf_settings.sh"
rm -rf "$ASF_TMP"
echo "  ✓ ASF installed"

# ── Step 5: Install qiskit-fermions ──────────────────────────────────────────
echo "[5/6] Installing qiskit-fermions (Rust compilation)..."
QF_TMP=$(mktemp -d)
git clone https://github.com/Qiskit/qiskit-fermions.git "$QF_TMP"
cd "$QF_TMP"
pip install --group build
pip install --no-build-isolation .
cd -
rm -rf "$QF_TMP"
echo "  ✓ qiskit-fermions installed"

# ── Step 6: Install quenais ───────────────────────────────────────────────────
echo "[6/6] Installing quenais..."
cd "$(dirname "$0")"
pip install -e ".[quantum]"
echo "  ✓ quenais installed"

# ── Verify ────────────────────────────────────────────────────────────────────
echo ""
echo "=== Verifying Installation ==="
python -c "import quenais;                              print('  ✓ quenais')"
python -c "import pyscf;                                print('  ✓ pyscf')"
python -c "import block2;                               print('  ✓ block2')"
python -c "import qiskit;                               print('  ✓ qiskit')"
python -c "import qiskit_aer;                           print('  ✓ qiskit-aer')"
python -c "import qiskit_addon_sqd;                     print('  ✓ qiskit-addon-sqd')"
python -c "import ffsim;                                print('  ✓ ffsim')"
python -c "from asf.wrapper import find_from_scf;       print('  ✓ asf')"
python -c "from qiskit_fermions.circuit import FermionicCircuit; print('  ✓ qiskit-fermions')"

echo ""
echo "=== Installation Complete ==="
echo "  block2 wrapper : $WRAPPER_PATH"
echo "  Run pipeline   : quenais-run --help"