"""
Regenerate the block2main wrapper for the current environment.
Run this whenever you switch conda environments.

    python -m quenais.utils.regenerate_wrapper
"""

import os
import sys
import subprocess
import glob


def regenerate(wrapper_path=None):
    if wrapper_path is None:
        wrapper_path = os.path.expanduser("~/block2main_wrapper.sh")

    try:
        import block2
    except ImportError:
        print("ERROR: block2 not installed in current environment.")
        print("  Run: pip install block2==0.5.2")
        return False

    import site as _site
    block2_dir  = os.path.dirname(block2.__file__)

    # block2.libs can be in two places depending on how block2 was built:
    # 1. site-packages/block2.libs  (pip wheel, most common)
    # 2. site-packages/block2_dir.libs  (editable install)
    _sp = _site.getsitepackages()[0]
    _candidate1 = os.path.join(_sp, "block2.libs")
    _candidate2 = block2_dir + ".libs"

    if os.path.exists(_candidate1):
        block2_libs = _candidate1
    elif os.path.exists(_candidate2):
        block2_libs = _candidate2
    else:
        block2_libs = _candidate1   # default, may not exist

    # This line must be at this indentation level — NOT inside the else block
    block2main = os.path.join(os.path.dirname(sys.executable), "block2main")

    if not os.path.exists(block2main):
        print(f"ERROR: block2main not found at {block2main}")
        return False

    # Detect CPU vendor
    try:
        cpu_vendor = subprocess.check_output(
            ["grep", "-m1", "vendor_id", "/proc/cpuinfo"], text=True
        ).split()[-1]
    except Exception:
        cpu_vendor = "unknown"

    # Check if MKL libraries actually exist
    mkl_libs = glob.glob(os.path.join(block2_libs, "libmkl_core*.so*"))
    has_mkl  = len(mkl_libs) > 0

    print(f"  Current env : {os.path.dirname(sys.executable)}")
    print(f"  block2_libs : {block2_libs}")
    print(f"  block2main  : {block2main}")
    print(f"  CPU vendor  : {cpu_vendor}")
    print(f"  MKL present : {has_mkl}")
    print(f"  Wrapper     : {wrapper_path}")

    env_dir = os.path.dirname(sys.executable)

    if cpu_vendor == "AuthenticAMD" and has_mkl:
        # Find actual library names dynamically
        def _find(pattern):
            matches = glob.glob(os.path.join(block2_libs, pattern))
            return matches[0] if matches else ""

        gomp    = _find("libgomp*.so*")
        avx2    = _find("libmkl_avx2*.so*")
        avx512  = _find("libmkl_avx512*.so*")
        core    = _find("libmkl_core*.so*")
        gnu     = _find("libmkl_gnu_thread*.so*")
        lp64    = _find("libmkl_intel_lp64*.so*")

        content = f"""#!/bin/bash

# Auto-generated by quenais.utils.regenerate_wrapper

# Environment : {env_dir}

# CPU         : AMD + MKL block2

export LD_PRELOAD="{gomp}:{avx2}:{avx512}:{core}:{gnu}:{lp64}"
export MKL_THREADING_LAYER=GNU
export MKL_DEBUG_CPU_TYPE=5
export LD_LIBRARY_PATH={block2_libs}:$LD_LIBRARY_PATH
exec {block2main} "$@"
"""
        print("  Mode: AMD + MKL workaround")

    elif cpu_vendor == "AuthenticAMD" and not has_mkl:
        content = f"""#!/bin/bash

# Auto-generated by quenais.utils.regenerate_wrapper

# Environment : {env_dir}

# CPU         : AMD + OpenBLAS block2 (no MKL workaround needed)

export MKL_THREADING_LAYER=GNU
export LD_LIBRARY_PATH={block2_libs}:$LD_LIBRARY_PATH
exec {block2main} "$@"
"""
        print("  Mode: AMD + OpenBLAS (simple wrapper)")

    else:
        content = f"""#!/bin/bash
# Auto-generated by quenais.utils.regenerate_wrapper

# Environment : {env_dir}

exec {block2main} "$@"
"""
        print("  Mode: Intel/other CPU (simple wrapper)")

    with open(wrapper_path, "w") as f:
        f.write(content)
    os.chmod(wrapper_path, 0o755)
    print(f"  ✓ Wrapper written to {wrapper_path}")
    print()
    print("  Contents:")
    print(content)
    return True


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(
        description="Regenerate block2main wrapper for current environment"
    )
    parser.add_argument("--path", default=None,
                        help="Path for wrapper (default: ~/block2main_wrapper.sh)")
    args  = parser.parse_args()
    success = regenerate(args.path)
    if not success:
        sys.exit(1)